version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
  db:
    image: postgres:latest
    environment: 
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/foo

volumes:
  db-data: